version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ya_analytics_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 10s       # Интервал проверок
      timeout: 5s         # Максимальное время ожидания отклика
      retries: 5          # Количество попыток
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_net

  app:
    build: .
    container_name: ya_analytics_app
    depends_on:
      db:
        condition: service_healthy  # Запустить app только после успешного health check
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_KEY: ${API_KEY}
      MODEL_URI: ${MODEL_URI}
    ports:
      - "8080:8080"
    volumes:
      - tmp_storage:/app/tmp
    networks:
      - backend_net

networks:
  backend_net:

volumes:
  pg_data:
  tmp_storage: